In [1]:
import numpy as np
import os


### nlabels500

In [2]:
nlabels500_CIFAR10ContaminationLevel25_u_train_dir = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/FixAStep_PublicRepo/fix-a-step/ML_DATA/CIFAR10Contamination_ssl/unnormalized_HWC/cifar10/data_seed0/nlabels500/CIFAR10ContaminationLevel25'
nlabels500_CIFAR10ContaminationLevel50_u_train_dir = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/FixAStep_PublicRepo/fix-a-step/ML_DATA/CIFAR10Contamination_ssl/unnormalized_HWC/cifar10/data_seed0/nlabels500/CIFAR10ContaminationLevel50'
nlabels500_CIFAR10ContaminationLevel75_u_train_dir = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/FixAStep_PublicRepo/fix-a-step/ML_DATA/CIFAR10Contamination_ssl/unnormalized_HWC/cifar10/data_seed0/nlabels500/CIFAR10ContaminationLevel75'




#### 2. Create CIFAR10ContaminationLevel25/u_train_oracle.npy

In [3]:
nlabels500_CIFAR10ContaminationLevel25_u_train_path = os.path.join(nlabels500_CIFAR10ContaminationLevel25_u_train_dir, 'u_train.npy')
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_path = os.path.join(nlabels500_CIFAR10ContaminationLevel25_u_train_dir, 'u_train_oracle.npy')


In [4]:
nlabels500_CIFAR10ContaminationLevel25_u_train = np.load(nlabels500_CIFAR10ContaminationLevel25_u_train_path, allow_pickle=True).item()


In [5]:
nlabels500_CIFAR10ContaminationLevel25_u_train

{'images': array([[[[171, 118,  69],
          [170, 117,  68],
          [169, 116,  67],
          ...,
          [177, 119,  78],
          [172, 118,  75],
          [171, 121,  74]],
 
         [[154,  91,  44],
          [151,  93,  45],
          [150,  92,  46],
          ...,
          [161,  98,  48],
          [151,  99,  46],
          [150,  99,  50]],
 
         [[113,  62,  27],
          [113,  63,  28],
          [114,  63,  28],
          ...,
          [127,  69,  29],
          [120,  69,  27],
          [119,  70,  30]],
 
         ...,
 
         [[119,  94,  71],
          [120,  92,  70],
          [124,  94,  73],
          ...,
          [ 94, 102,  58],
          [ 85, 102,  54],
          [ 83, 100,  50]],
 
         [[114,  97,  78],
          [116,  97,  75],
          [121, 100,  79],
          ...,
          [123, 103,  75],
          [116, 102,  72],
          [111,  99,  66]],
 
         [[102,  95,  61],
          [102,  95,  61],
          [104,  96,

In [6]:
print('nlabels500_CIFAR10ContaminationLevel25_u_train images shape: {}'.format(nlabels500_CIFAR10ContaminationLevel25_u_train['images'].shape))
print('nlabels500_CIFAR10ContaminationLevel25_u_train labels shape: {}'.format(nlabels500_CIFAR10ContaminationLevel25_u_train['labels'].shape))
print('nlabels500_CIFAR10ContaminationLevel25_u_train labels: {}'.format(set(nlabels500_CIFAR10ContaminationLevel25_u_train['labels'])))



nlabels500_CIFAR10ContaminationLevel25_u_train images shape: (17800, 32, 32, 3)
nlabels500_CIFAR10ContaminationLevel25_u_train labels shape: (17800,)
nlabels500_CIFAR10ContaminationLevel25_u_train labels: {0, 5, 6, 7}


In [7]:
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_mask = nlabels500_CIFAR10ContaminationLevel25_u_train['labels'] != 0
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_mask

array([False, False, False, ...,  True,  True,  True])

In [8]:
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_images = nlabels500_CIFAR10ContaminationLevel25_u_train['images'][nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_mask]
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_labels = nlabels500_CIFAR10ContaminationLevel25_u_train['labels'][nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_mask]
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle = {"images": nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_images,
                                                        "labels": nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_labels}


In [9]:
print('nlabels500_CIFAR10ContaminationLevel25_u_train_oracle images shape: {}'.format(nlabels500_CIFAR10ContaminationLevel25_u_train_oracle['images'].shape))
print('nlabels500_CIFAR10ContaminationLevel25_u_train_oracle labels shape: {}'.format(nlabels500_CIFAR10ContaminationLevel25_u_train_oracle['labels'].shape))
print('nlabels500_CIFAR10ContaminationLevel25_u_train_oracle labels: {}'.format(set(nlabels500_CIFAR10ContaminationLevel25_u_train_oracle['labels'])))



nlabels500_CIFAR10ContaminationLevel25_u_train_oracle images shape: (13350, 32, 32, 3)
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle labels shape: (13350,)
nlabels500_CIFAR10ContaminationLevel25_u_train_oracle labels: {5, 6, 7}


In [10]:
np.save(nlabels500_CIFAR10ContaminationLevel25_u_train_oracle_path, nlabels500_CIFAR10ContaminationLevel25_u_train_oracle)



#### 2. Create CIFAR10ContaminationLevel50/u_train_oracle.npy

In [11]:
nlabels500_CIFAR10ContaminationLevel50_u_train_path = os.path.join(nlabels500_CIFAR10ContaminationLevel50_u_train_dir, 'u_train.npy')
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_path = os.path.join(nlabels500_CIFAR10ContaminationLevel50_u_train_dir, 'u_train_oracle.npy')


In [12]:
nlabels500_CIFAR10ContaminationLevel50_u_train = np.load(nlabels500_CIFAR10ContaminationLevel50_u_train_path, allow_pickle=True).item()


In [13]:
nlabels500_CIFAR10ContaminationLevel50_u_train

{'images': array([[[[171, 118,  69],
          [170, 117,  68],
          [169, 116,  67],
          ...,
          [177, 119,  78],
          [172, 118,  75],
          [171, 121,  74]],
 
         [[154,  91,  44],
          [151,  93,  45],
          [150,  92,  46],
          ...,
          [161,  98,  48],
          [151,  99,  46],
          [150,  99,  50]],
 
         [[113,  62,  27],
          [113,  63,  28],
          [114,  63,  28],
          ...,
          [127,  69,  29],
          [120,  69,  27],
          [119,  70,  30]],
 
         ...,
 
         [[119,  94,  71],
          [120,  92,  70],
          [124,  94,  73],
          ...,
          [ 94, 102,  58],
          [ 85, 102,  54],
          [ 83, 100,  50]],
 
         [[114,  97,  78],
          [116,  97,  75],
          [121, 100,  79],
          ...,
          [123, 103,  75],
          [116, 102,  72],
          [111,  99,  66]],
 
         [[102,  95,  61],
          [102,  95,  61],
          [104,  96,

In [14]:
print('nlabels500_CIFAR10ContaminationLevel50_u_train images shape: {}'.format(nlabels500_CIFAR10ContaminationLevel50_u_train['images'].shape))
print('nlabels500_CIFAR10ContaminationLevel50_u_train labels shape: {}'.format(nlabels500_CIFAR10ContaminationLevel50_u_train['labels'].shape))
print('nlabels500_CIFAR10ContaminationLevel50_u_train labels: {}'.format(set(nlabels500_CIFAR10ContaminationLevel50_u_train['labels'])))



nlabels500_CIFAR10ContaminationLevel50_u_train images shape: (17800, 32, 32, 3)
nlabels500_CIFAR10ContaminationLevel50_u_train labels shape: (17800,)
nlabels500_CIFAR10ContaminationLevel50_u_train labels: {0, 1, 6, 7}


In [15]:
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_mask = (nlabels500_CIFAR10ContaminationLevel50_u_train['labels'] != 0) & (nlabels500_CIFAR10ContaminationLevel50_u_train['labels'] != 1)
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_mask

array([False, False, False, ...,  True,  True,  True])

In [16]:
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_images = nlabels500_CIFAR10ContaminationLevel50_u_train['images'][nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_mask]
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_labels = nlabels500_CIFAR10ContaminationLevel50_u_train['labels'][nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_mask]
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle = {"images": nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_images,
                                                        "labels": nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_labels}


In [17]:
print('nlabels500_CIFAR10ContaminationLevel50_u_train_oracle images shape: {}'.format(nlabels500_CIFAR10ContaminationLevel50_u_train_oracle['images'].shape))
print('nlabels500_CIFAR10ContaminationLevel50_u_train_oracle labels shape: {}'.format(nlabels500_CIFAR10ContaminationLevel50_u_train_oracle['labels'].shape))
print('nlabels500_CIFAR10ContaminationLevel50_u_train_oracle labels: {}'.format(set(nlabels500_CIFAR10ContaminationLevel50_u_train_oracle['labels'])))



nlabels500_CIFAR10ContaminationLevel50_u_train_oracle images shape: (8900, 32, 32, 3)
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle labels shape: (8900,)
nlabels500_CIFAR10ContaminationLevel50_u_train_oracle labels: {6, 7}


In [18]:
np.save(nlabels500_CIFAR10ContaminationLevel50_u_train_oracle_path, nlabels500_CIFAR10ContaminationLevel50_u_train_oracle)



#### 2. Create CIFAR10ContaminationLevel75/u_train_oracle.npy

In [19]:
nlabels500_CIFAR10ContaminationLevel75_u_train_path = os.path.join(nlabels500_CIFAR10ContaminationLevel75_u_train_dir, 'u_train.npy')
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_path = os.path.join(nlabels500_CIFAR10ContaminationLevel75_u_train_dir, 'u_train_oracle.npy')


In [20]:
nlabels500_CIFAR10ContaminationLevel75_u_train = np.load(nlabels500_CIFAR10ContaminationLevel75_u_train_path, allow_pickle=True).item()


In [21]:
nlabels500_CIFAR10ContaminationLevel75_u_train

{'images': array([[[[171, 118,  69],
          [170, 117,  68],
          [169, 116,  67],
          ...,
          [177, 119,  78],
          [172, 118,  75],
          [171, 121,  74]],
 
         [[154,  91,  44],
          [151,  93,  45],
          [150,  92,  46],
          ...,
          [161,  98,  48],
          [151,  99,  46],
          [150,  99,  50]],
 
         [[113,  62,  27],
          [113,  63,  28],
          [114,  63,  28],
          ...,
          [127,  69,  29],
          [120,  69,  27],
          [119,  70,  30]],
 
         ...,
 
         [[119,  94,  71],
          [120,  92,  70],
          [124,  94,  73],
          ...,
          [ 94, 102,  58],
          [ 85, 102,  54],
          [ 83, 100,  50]],
 
         [[114,  97,  78],
          [116,  97,  75],
          [121, 100,  79],
          ...,
          [123, 103,  75],
          [116, 102,  72],
          [111,  99,  66]],
 
         [[102,  95,  61],
          [102,  95,  61],
          [104,  96,

In [22]:
print('nlabels500_CIFAR10ContaminationLevel75_u_train images shape: {}'.format(nlabels500_CIFAR10ContaminationLevel75_u_train['images'].shape))
print('nlabels500_CIFAR10ContaminationLevel75_u_train labels shape: {}'.format(nlabels500_CIFAR10ContaminationLevel75_u_train['labels'].shape))
print('nlabels500_CIFAR10ContaminationLevel75_u_train labels: {}'.format(set(nlabels500_CIFAR10ContaminationLevel75_u_train['labels'])))



nlabels500_CIFAR10ContaminationLevel75_u_train images shape: (17800, 32, 32, 3)
nlabels500_CIFAR10ContaminationLevel75_u_train labels shape: (17800,)
nlabels500_CIFAR10ContaminationLevel75_u_train labels: {0, 1, 8, 7}


In [23]:
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_mask = (nlabels500_CIFAR10ContaminationLevel75_u_train['labels'] != 0) & (nlabels500_CIFAR10ContaminationLevel75_u_train['labels'] != 1) & (nlabels500_CIFAR10ContaminationLevel75_u_train['labels'] != 8)
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_mask

array([False, False, False, ..., False, False, False])

In [24]:
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_images = nlabels500_CIFAR10ContaminationLevel75_u_train['images'][nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_mask]
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_labels = nlabels500_CIFAR10ContaminationLevel75_u_train['labels'][nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_mask]
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle = {"images": nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_images,
                                                        "labels": nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_labels}


In [25]:
print('nlabels500_CIFAR10ContaminationLevel75_u_train_oracle images shape: {}'.format(nlabels500_CIFAR10ContaminationLevel75_u_train_oracle['images'].shape))
print('nlabels500_CIFAR10ContaminationLevel75_u_train_oracle labels shape: {}'.format(nlabels500_CIFAR10ContaminationLevel75_u_train_oracle['labels'].shape))
print('nlabels500_CIFAR10ContaminationLevel75_u_train_oracle labels: {}'.format(set(nlabels500_CIFAR10ContaminationLevel75_u_train_oracle['labels'])))



nlabels500_CIFAR10ContaminationLevel75_u_train_oracle images shape: (4450, 32, 32, 3)
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle labels shape: (4450,)
nlabels500_CIFAR10ContaminationLevel75_u_train_oracle labels: {7}


In [26]:
np.save(nlabels500_CIFAR10ContaminationLevel75_u_train_oracle_path, nlabels500_CIFAR10ContaminationLevel75_u_train_oracle)

