In [1]:
import numpy as np
import os


### nlabels4000

In [2]:
nlabels4000_CIFAR10ContaminationLevel25_u_train_dir = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/FixAStep_PublicRepo/fix-a-step/ML_DATA/CIFAR10Contamination_ssl/unnormalized_HWC/cifar10/data_seed0/nlabels4000/CIFAR10ContaminationLevel25'
nlabels4000_CIFAR10ContaminationLevel50_u_train_dir = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/FixAStep_PublicRepo/fix-a-step/ML_DATA/CIFAR10Contamination_ssl/unnormalized_HWC/cifar10/data_seed0/nlabels4000/CIFAR10ContaminationLevel50'
nlabels4000_CIFAR10ContaminationLevel75_u_train_dir = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/FixAStep_PublicRepo/fix-a-step/ML_DATA/CIFAR10Contamination_ssl/unnormalized_HWC/cifar10/data_seed0/nlabels4000/CIFAR10ContaminationLevel75'




#### 2. Create CIFAR10ContaminationLevel25/u_train_oracle.npy

In [3]:
nlabels4000_CIFAR10ContaminationLevel25_u_train_path = os.path.join(nlabels4000_CIFAR10ContaminationLevel25_u_train_dir, 'u_train.npy')
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_path = os.path.join(nlabels4000_CIFAR10ContaminationLevel25_u_train_dir, 'u_train_oracle.npy')


In [4]:
nlabels4000_CIFAR10ContaminationLevel25_u_train = np.load(nlabels4000_CIFAR10ContaminationLevel25_u_train_path, allow_pickle=True).item()


In [5]:
nlabels4000_CIFAR10ContaminationLevel25_u_train

{'images': array([[[[128,  94,  59],
          [128,  96,  58],
          [130,  99,  58],
          ...,
          [152, 118,  84],
          [154, 120,  88],
          [152, 118,  88]],
 
         [[126,  93,  58],
          [126,  94,  56],
          [125,  94,  53],
          ...,
          [158, 122,  88],
          [157, 122,  90],
          [154, 118,  89]],
 
         [[124,  91,  56],
          [126,  94,  56],
          [128,  96,  55],
          ...,
          [159, 121,  88],
          [158, 121,  90],
          [157, 119,  91]],
 
         ...,
 
         [[115,  69,  43],
          [114,  67,  41],
          [104,  54,  29],
          ...,
          [174, 129, 101],
          [173, 129, 103],
          [169, 128, 104]],
 
         [[116,  69,  41],
          [118,  68,  41],
          [117,  63,  38],
          ...,
          [183, 133, 102],
          [179, 131, 103],
          [175, 129, 103]],
 
         [[120,  71,  40],
          [122,  70,  41],
          [126,  70,

In [6]:
print('nlabels4000_CIFAR10ContaminationLevel25_u_train images shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel25_u_train['images'].shape))
print('nlabels4000_CIFAR10ContaminationLevel25_u_train labels shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel25_u_train['labels'].shape))
print('nlabels4000_CIFAR10ContaminationLevel25_u_train labels: {}'.format(set(nlabels4000_CIFAR10ContaminationLevel25_u_train['labels'])))



nlabels4000_CIFAR10ContaminationLevel25_u_train images shape: (16400, 32, 32, 3)
nlabels4000_CIFAR10ContaminationLevel25_u_train labels shape: (16400,)
nlabels4000_CIFAR10ContaminationLevel25_u_train labels: {0, 5, 6, 7}


In [7]:
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_mask = nlabels4000_CIFAR10ContaminationLevel25_u_train['labels'] != 0
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_mask

array([False, False, False, ...,  True,  True,  True])

In [8]:
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_images = nlabels4000_CIFAR10ContaminationLevel25_u_train['images'][nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_mask]
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_labels = nlabels4000_CIFAR10ContaminationLevel25_u_train['labels'][nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_mask]
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle = {"images": nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_images,
                                                        "labels": nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_labels}


In [9]:
print('nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle images shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle['images'].shape))
print('nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle labels shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle['labels'].shape))
print('nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle labels: {}'.format(set(nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle['labels'])))



nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle images shape: (12300, 32, 32, 3)
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle labels shape: (12300,)
nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle labels: {5, 6, 7}


In [10]:
np.save(nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle_path, nlabels4000_CIFAR10ContaminationLevel25_u_train_oracle)



#### 2. Create CIFAR10ContaminationLevel50/u_train_oracle.npy

In [11]:
nlabels4000_CIFAR10ContaminationLevel50_u_train_path = os.path.join(nlabels4000_CIFAR10ContaminationLevel50_u_train_dir, 'u_train.npy')
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_path = os.path.join(nlabels4000_CIFAR10ContaminationLevel50_u_train_dir, 'u_train_oracle.npy')


In [12]:
nlabels4000_CIFAR10ContaminationLevel50_u_train = np.load(nlabels4000_CIFAR10ContaminationLevel50_u_train_path, allow_pickle=True).item()


In [13]:
nlabels4000_CIFAR10ContaminationLevel50_u_train

{'images': array([[[[128,  94,  59],
          [128,  96,  58],
          [130,  99,  58],
          ...,
          [152, 118,  84],
          [154, 120,  88],
          [152, 118,  88]],
 
         [[126,  93,  58],
          [126,  94,  56],
          [125,  94,  53],
          ...,
          [158, 122,  88],
          [157, 122,  90],
          [154, 118,  89]],
 
         [[124,  91,  56],
          [126,  94,  56],
          [128,  96,  55],
          ...,
          [159, 121,  88],
          [158, 121,  90],
          [157, 119,  91]],
 
         ...,
 
         [[115,  69,  43],
          [114,  67,  41],
          [104,  54,  29],
          ...,
          [174, 129, 101],
          [173, 129, 103],
          [169, 128, 104]],
 
         [[116,  69,  41],
          [118,  68,  41],
          [117,  63,  38],
          ...,
          [183, 133, 102],
          [179, 131, 103],
          [175, 129, 103]],
 
         [[120,  71,  40],
          [122,  70,  41],
          [126,  70,

In [14]:
print('nlabels4000_CIFAR10ContaminationLevel50_u_train images shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel50_u_train['images'].shape))
print('nlabels4000_CIFAR10ContaminationLevel50_u_train labels shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel50_u_train['labels'].shape))
print('nlabels4000_CIFAR10ContaminationLevel50_u_train labels: {}'.format(set(nlabels4000_CIFAR10ContaminationLevel50_u_train['labels'])))



nlabels4000_CIFAR10ContaminationLevel50_u_train images shape: (16400, 32, 32, 3)
nlabels4000_CIFAR10ContaminationLevel50_u_train labels shape: (16400,)
nlabels4000_CIFAR10ContaminationLevel50_u_train labels: {0, 1, 6, 7}


In [15]:
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_mask = (nlabels4000_CIFAR10ContaminationLevel50_u_train['labels'] != 0) & (nlabels4000_CIFAR10ContaminationLevel50_u_train['labels'] != 1)
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_mask

array([False, False, False, ...,  True,  True,  True])

In [16]:
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_images = nlabels4000_CIFAR10ContaminationLevel50_u_train['images'][nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_mask]
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_labels = nlabels4000_CIFAR10ContaminationLevel50_u_train['labels'][nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_mask]
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle = {"images": nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_images,
                                                        "labels": nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_labels}


In [17]:
print('nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle images shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle['images'].shape))
print('nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle labels shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle['labels'].shape))
print('nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle labels: {}'.format(set(nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle['labels'])))



nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle images shape: (8200, 32, 32, 3)
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle labels shape: (8200,)
nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle labels: {6, 7}


In [18]:
np.save(nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle_path, nlabels4000_CIFAR10ContaminationLevel50_u_train_oracle)



#### 2. Create CIFAR10ContaminationLevel75/u_train_oracle.npy

In [19]:
nlabels4000_CIFAR10ContaminationLevel75_u_train_path = os.path.join(nlabels4000_CIFAR10ContaminationLevel75_u_train_dir, 'u_train.npy')
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_path = os.path.join(nlabels4000_CIFAR10ContaminationLevel75_u_train_dir, 'u_train_oracle.npy')


In [20]:
nlabels4000_CIFAR10ContaminationLevel75_u_train = np.load(nlabels4000_CIFAR10ContaminationLevel75_u_train_path, allow_pickle=True).item()


In [21]:
nlabels4000_CIFAR10ContaminationLevel75_u_train

{'images': array([[[[128,  94,  59],
          [128,  96,  58],
          [130,  99,  58],
          ...,
          [152, 118,  84],
          [154, 120,  88],
          [152, 118,  88]],
 
         [[126,  93,  58],
          [126,  94,  56],
          [125,  94,  53],
          ...,
          [158, 122,  88],
          [157, 122,  90],
          [154, 118,  89]],
 
         [[124,  91,  56],
          [126,  94,  56],
          [128,  96,  55],
          ...,
          [159, 121,  88],
          [158, 121,  90],
          [157, 119,  91]],
 
         ...,
 
         [[115,  69,  43],
          [114,  67,  41],
          [104,  54,  29],
          ...,
          [174, 129, 101],
          [173, 129, 103],
          [169, 128, 104]],
 
         [[116,  69,  41],
          [118,  68,  41],
          [117,  63,  38],
          ...,
          [183, 133, 102],
          [179, 131, 103],
          [175, 129, 103]],
 
         [[120,  71,  40],
          [122,  70,  41],
          [126,  70,

In [22]:
print('nlabels4000_CIFAR10ContaminationLevel75_u_train images shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel75_u_train['images'].shape))
print('nlabels4000_CIFAR10ContaminationLevel75_u_train labels shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel75_u_train['labels'].shape))
print('nlabels4000_CIFAR10ContaminationLevel75_u_train labels: {}'.format(set(nlabels4000_CIFAR10ContaminationLevel75_u_train['labels'])))



nlabels4000_CIFAR10ContaminationLevel75_u_train images shape: (16400, 32, 32, 3)
nlabels4000_CIFAR10ContaminationLevel75_u_train labels shape: (16400,)
nlabels4000_CIFAR10ContaminationLevel75_u_train labels: {0, 1, 8, 7}


In [23]:
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_mask = (nlabels4000_CIFAR10ContaminationLevel75_u_train['labels'] != 0) & (nlabels4000_CIFAR10ContaminationLevel75_u_train['labels'] != 1) & (nlabels4000_CIFAR10ContaminationLevel75_u_train['labels'] != 8)
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_mask

array([False, False, False, ..., False, False, False])

In [24]:
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_images = nlabels4000_CIFAR10ContaminationLevel75_u_train['images'][nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_mask]
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_labels = nlabels4000_CIFAR10ContaminationLevel75_u_train['labels'][nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_mask]
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle = {"images": nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_images,
                                                        "labels": nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_labels}


In [25]:
print('nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle images shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle['images'].shape))
print('nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle labels shape: {}'.format(nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle['labels'].shape))
print('nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle labels: {}'.format(set(nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle['labels'])))



nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle images shape: (4100, 32, 32, 3)
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle labels shape: (4100,)
nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle labels: {7}


In [26]:
np.save(nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle_path, nlabels4000_CIFAR10ContaminationLevel75_u_train_oracle)

